---
# What container runtime do we use?
# valid values:
# - docker
# - crio
container_runtime: docker

# Pod net work types
# A value of "none" will create no networking and will not join minions to cluster.
# Valid values:
# - flannel
# - weave
# - none
# - multus
pod_network_type: "flannel"
pod_network_cidr: "10.244.0.0"

# General config

# At 1.7.2 you need this cause of a bug in kubeadm join.
# Turn it off later, or, try it if a join fails.
skip_preflight_checks: true

# Stable. (was busted at 1.6 release, may work now, untested for a couple months)
kube_baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64

# Unstable
# kube_baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64-unstable

centos_genericcloud_url: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1611.qcow2"
image_destination_name: CentOS-7-x86_64-GenericCloud.qcow2
images_directory: /home/images
bridge_name: virbr0
virtual_machines:
  - kube-master
  - kube-minion-1
  - kube-minion-2
  - kube-minion-3
vm_parameters:
  ram_mb: 2048
  cpus: 4

# Kubernetes 1.6 additions
kubectl_user: centos
kubectl_group: centos
kubectl_home: /home/centos

# Implement a work-around for this:
# https://github.com/kubernetes/kubernetes/issues/43815
kube_16_workaround: false

# --------------------------- -
# multus-cni vars          - -
# ------------------------- -
multus_ipam_subnet: "192.168.122.0/24"
multus_ipam_rangeStart: "192.168.122.200"
multus_ipam_rangeEnd: "192.168.122.216"
multus_ipam_gateway: "192.168.122.1"

# ----------------------------
# glusterfs vars
# ----------------------------
spare_disk_size_megs: 10240
spare_disk_location: "/var/lib/libvirt/images"
spare_disk_dev: vdb
# Default size is megs, "2G" would be 2 gigs.
brick_size: "1980"

# ----------------------------
# virt-host vars.
# ----------------------------
# Enables a bridge to the outside LAN
# (as opposed to using virbr0)
bridge_networking: true
bridge_physical_nic: "enp1s0f1"
bridge_network_name: "br0"
bridge_network_cidr: 192.168.1.0/24