---

- name: Template CRD flavored multus.yaml
  template:
    src: multus-crd.yaml.j2
    dest: /etc/multus-crd.yaml
  when: pod_network_type == 'multus' or pod_network_type == 'multus-2nics'

- name: Template flannel.yaml
  template:
    src: flannel.yaml.j2
    dest: /etc/flannel.yaml

- name: Template flannel-rbac.yaml
  template:
    src: flannel-rbac.yaml.j2
    dest: /etc/flannel-rbac.yaml

- name: Template bridge.yaml
  template:
    src: bridge.yaml.j2
    dest: /etc/bridge.yaml

- name: Template calico-rbac.yaml
  template:
    src: calico-rbac.yaml.j2
    dest: /etc/calico-rbac.yaml
  when: pod_network_type == 'calico'

- name: Template calico.yaml
  template:
    src: calico.yaml.j2
    dest: /etc/calico.yaml
  when: pod_network_type == 'calico'
