---
- hosts: all_vms
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: glusterfs-install }

- hosts: master
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: glusterfs-probe-peers }
    - { role: glusterfs-create-volume, volume_appendix: 1 }
    - { role: glusterfs-create-volume, volume_appendix: 2 }
    - { role: glusterfs-create-volume, volume_appendix: 3 }
    - { role: glusterfs-create-volume, volume_appendix: 4 }
    - { role: glusterfs-create-volume, volume_appendix: 5 }

- hosts: master
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: glusterfs-kube-config }
