---
- hosts: all_vms
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: glusterfs-install }

- hosts: master
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: glusterfs-probe-peers }
