---
- hosts: all_vms
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    # - { role: docker-install }
    # You can add "crio_force: true" if you need to run the builds again.
    - { role: cri-o-install, when: container_runtime == 'crio', crio_force: false }
    - { role: kube-install }
    - { role: multus-cni, when: pod_network_type == "multus" }

- hosts: master
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: kube-init }
    - { role: kube-template-cni }

# ---- placeholder: kube-cni
# without become.

- hosts: master
  vars_files:
    - vars/all.yml
  vars:
    kubectl_environment:
      KUBECONFIG: "{{ kubectl_home }}/admin.conf"
  tasks: []
  roles:
    - { role: kube-cni }


- hosts: minions
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  pre_tasks:
    - name: Get kubeadm_join_command from master
      set_fact:
        kubeadm_join_command: "{{ hostvars[groups['master'][0]]['kubeadm_join_command'] }}"
  tasks: []
  roles:
    - { role: kube-join-cluster }
