---
- src: https://github.com/redhat-nfvpe/ansible-role-install-go
  name: install-go
  version: master
- src: https://github.com/redhat-nfvpe/ansible-role-install-docker
  name: install-docker
  version: master
