---

# Based on: https://wiki.centos.org/HowTos/GlusterFSonCentOS

- name: Install latest EPEL
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Enable GlusterFS repo
  yum:
    name: centos-release-gluster38
    state: present

- name: Install required packages for GlusterFS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs
    - glusterfs-cli
    - glusterfs-libs
    - glusterfs-server
    - samba

- include: setup_partitions.yml
  when: "1 == 0"

- name: Start gluster service
  service:
    name: glusterd
    state: started
    enabled: yes