---
- name: create /etc/cni/multus/net.d
  file:
    path: /etc/cni/multus/net.d
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755

- name: Configure eth1 for data plane
  template:
    src: ifcfg-eth1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
  notify: "restart eth1"

- name: Configure eth1.1 for data plane
  template:
    src: ifcfg-eth1.1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1.1
  notify: "restart eth1.1"
  when: "'master' in group_names"
