---
# ---------------------------------------
# This is flannel plain                -
# ---------------------------------------

# More info here: https://kubernetes.io/docs/admin/addons/
# I got the template from: https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml
# I got a lot of help from https://github.com/kubernetes/kubernetes/issues/36575

- name: Template flannel.yaml
  template:
    src: flannel.yaml.j2
    dest: /etc/flannel.yaml

- name: Apply the podnetwork
  shell: >
    kubectl apply -f /etc/flannel.yaml > /var/log/podnetwork-apply.log
  args:
    creates: /etc/.kubeadm-podnetwork-complete