---
- name: Installs deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: Clone cni-plugins
  git:
    repo: https://github.com/containernetworking/plugins
    dest: /usr/src/cni-plugins
    version: master
  register: cni_clone

- name: Compile cni-plugins
  shell: >
    ./build_linux.sh
  args:
    chdir: /usr/src/cni-plugins
  when: cni_clone.changed

- name: Clone multus-cni
  git:
    repo: "{{ multus_git_url }}"
    dest: /usr/src/multus-cni
    version: "{{ multus_version }}"
    force: true
  register: multus_clone

- name: Compile multus-cni
  shell: >
    ./build
  args:
    chdir: /usr/src/multus-cni
  when: multus_clone.changed or force_multus_rebuild is defined

- name: Install required packages for sriov-cni
  shell: >
    go get github.com/Masterminds/glide && \
    go install github.com/Masterminds/glide

- name: Clone sriov-cni
  git:
    repo: https://github.com/intel/sriov-cni.git
    dest: /usr/src/sriov-cni
    version: master
  register: sriov_clone

- name: Compile sriov-cni
  shell: >
    PATH=${PATH}:${GOPATH}/bin make
  args:
    chdir: /usr/src/sriov-cni
  when: sriov_clone.changed

- name: Copy compiled cni binaries
  shell: >
    cp {{ item }} /opt/cni/bin/
  with_items:
    - "/usr/src/cni-plugins/bin/*"
    - "/usr/src/sriov-cni/bin/*"
    - "/usr/src/multus-cni/bin/*"
