---

- name: "Disable SELinux :("
  selinux:
    state: disabled  

- name: "Stop iptables :("
  service:
    name: iptables
    state: stopped
  ignore_errors: yes

- name: "Disable iptables :("
  service:
    name: iptables
    enabled: no
  ignore_errors: yes

- name: Template kube RPM repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Include kube 1.6.0 work-around
  include: kube-16-workaround.yml
  when: kube_16_workaround

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - docker
    - kubelet
