---

- name: "Disable SELinux :("
  selinux:
    state: disabled

- name: "Stop iptables :("
  service:
    name: iptables
    state: stopped
  ignore_errors: yes

- name: "Disable iptables :("
  service:
    name: iptables
    enabled: no
  ignore_errors: yes

- name: Template kube RPM repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Install docker (when using docker mode)
  package:
    name: "docker"
    state: present
  when: "'{{ container_runtime }}' == 'docker'"

- name: Include kube 1.6.0 work-around
  include: kube-16-workaround.yml
  when: kube_16_workaround

- name: Remove default kubadm.conf ExecStart
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'KUBELET_EXTRA_ARGS$'
    state: absent

- name: Add custom kubadm.conf ExecStart
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'systemd$'
    line: 'ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS --cgroup-driver=systemd'

- name: Reload systemd units after changing 10-kubeadm.conf
  command: systemctl daemon-reload

- name: Start and enable kubelet
  service:
    name: "kubelet"
    state: restarted
    enabled: yes

- name: Start docker when appropriate
  service:
    name: "docker"
    state: restarted
    enabled: yes
  when: "'{{ container_runtime }}' == 'docker'"