---
- name: "Disable SELinux :("
  selinux:
    state: disabled

- name: "reboot machine"
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0

- name: "Wait for VM up"
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30

- name: "Stop iptables :("
  service:
    name: "{{ __firewall_service }}"
    state: stopped
  ignore_errors: yes

- name: "Disable iptables :("
  service:
    name: "{{ __firewall_service }}"
    enabled: no
  ignore_errors: yes
