---

- name: Remove NodeRestriction from kubelet config
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: NodeRestriction
    state: absent

- name: Add ComputeDevice featureGates to api server
  blockinfile:
    path: d
    block: |
        featureGates:
          ComputeDevice: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: cgroupDriver

- name: Restart the kubelet
  service:
    name: kubelet
    state: restarted
