---
- name: oVirt infra
  hosts: engine
  gather_facts: false

  tasks:
    - set_fact:
        vm_ssh_key: "{{ lookup('env', 'VM_SSH_KEY') }}"
        engine_user: "{{ lookup('env', 'ENGINE_CREDS_USR') }}"
        engine_password: "{{ lookup('env', 'ENGINE_CREDS_PSW') }}"

    - include_role:
        name: oVirt.vm-infra
