# Creates a systemd unit and starts kubectl proxy.
# https://kubernetes.io/docs/user-guide/kubectl/v1.8/#proxy

- name: Template kubectl proxy systemd unit
  template:
    src: kubectl-proxy.service.j2
    dest: /etc/systemd/system/kubectl-proxy.service
  register: template_kubectlproxy_unit

- name: Restart proxy when changed
  systemd:
    name: kubectl-proxy
    state: restarted
    daemon_reload: yes
  when: template_kubectlproxy_unit.changed

- name: Always ensure proxy is started
  systemd:
    name: kubectl-proxy
    state: started
    daemon_reload: yes
