---

- name: Ensure git is installed
  yum:
    name: git
    state: present

- name: Clone ehost-device-cni Plugin repo
  git:
    repo: https://github.com/zshi-redhat/ehost-device-cni.git
    dest: /usr/src/ehost-device-cni
    force: true

- name: Build it
  shell: >
    source /etc/profile.d/golang.sh;./build.sh
  args:
    chdir: /usr/src/ehost-device-cni

- name: Copy Userspace CNI plugin to CNI bin dir
  shell: >
    cp bin/ehost-device /opt/cni/bin/ehost-device
  args:
    chdir: /usr/src/ehost-device-cni
    creates: "/opt/cni/bin/ehost-device"
